print("What happens to an illegally parked frog?")
input("")
print("It gets toad away!")
input("")
print("What do you call a bear with no teeth?")
input("")
print("a gummy bear!")
input("")
print("why cant you trust an atom?")
input("")
print("because they make up everything!")